-- Backfill unificador_puesto y agrupador desde literal_puesto
-- para cargos que quedaron sin clasificar.
-- Aplicar: psql -U srrhh_user -d srrhh_db -f scripts/backfill_unificador_puesto.sql
UPDATE cargos SET
  unificador_puesto = CASE
    WHEN literal_puesto IN ('ESPECIALISTA EN LA GUARDIA MEDICO', 'PROFESIONAL GUARDIA MEDICO',
                            'BIOQUIMICO DE GUARDIA', 'FARMACEUTICO DE GUARDIA',
                            'KINESIOLOGO DE GUARDIA', 'ASISTENTE SOCIAL DE GUARDIA',
                            'PSICOLOGO DE GUARDIA', 'OBSTETRICA DE GUARDIA')
      THEN 'CPH DE GUARDIA'
    WHEN literal_puesto IN ('MEDICO DE PLANTA', 'PSICOLOGO DE PLANTA', 'ODONTOLOGO DE PLANTA',
                            'BIOQUIMICO DE PLANTA', 'FARMACEUTICO DE PLANTA', 'KINESIOLOGO DE PLANTA',
                            'ASISTENTE SOCIAL DE PLANTA', 'TERAPISTA OCUPACIONAL DE PLANTA',
                            'TRABAJADOR SOCIAL DE PLANTA', 'NUTRICIONISTA DE PLANTA',
                            'FONOAUDIOLOGO DE PLANTA', 'PSICOPEDAGOGO DE PLANTA',
                            'ODONTOLOGO DE GUARDIA', 'OBSTETRICA DE PLANTA',
                            'LIC. EN TERAPIA OCUPACIONAL DE PLANTA')
      THEN 'CPH DE PLANTA'
    WHEN literal_puesto = 'JEFE DE UNIDAD (05)'  THEN 'JEFE/A DE UNIDAD'
    WHEN literal_puesto = 'JEFE DE SECCION (06)' THEN 'JEFE/A DE SECCION'
    WHEN literal_puesto IN ('JEFE DE DIVISION (04)', 'JEFE DE DEPARTAMENTO (02)', 'SUB-DIRECTOR (03)')
      THEN literal_puesto
  END,
  agrupador = CASE
    WHEN literal_puesto IN ('ESPECIALISTA EN LA GUARDIA MEDICO', 'MEDICO DE PLANTA') THEN 'MEDICO'
    WHEN literal_puesto IN ('JEFE DE UNIDAD (05)', 'JEFE DE SECCION (06)',
                            'JEFE DE DIVISION (04)', 'JEFE DE DEPARTAMENTO (02)', 'SUB-DIRECTOR (03)')
      THEN 'JEFES CPH'
    ELSE 'NO MEDICO'
  END
WHERE (unificador_puesto IS NULL OR unificador_puesto = '')
  AND literal_puesto IN (
    'ESPECIALISTA EN LA GUARDIA MEDICO', 'MEDICO DE PLANTA', 'PROFESIONAL GUARDIA MEDICO',
    'JEFE DE UNIDAD (05)', 'JEFE DE SECCION (06)', 'PSICOLOGO DE PLANTA', 'ODONTOLOGO DE PLANTA',
    'BIOQUIMICO DE PLANTA', 'FARMACEUTICO DE PLANTA', 'JEFE DE DIVISION (04)', 'KINESIOLOGO DE PLANTA',
    'BIOQUIMICO DE GUARDIA', 'JEFE DE DEPARTAMENTO (02)', 'FARMACEUTICO DE GUARDIA',
    'KINESIOLOGO DE GUARDIA', 'ASISTENTE SOCIAL DE PLANTA', 'TERAPISTA OCUPACIONAL DE PLANTA',
    'ASISTENTE SOCIAL DE GUARDIA', 'TRABAJADOR SOCIAL DE PLANTA', 'NUTRICIONISTA DE PLANTA',
    'FONOAUDIOLOGO DE PLANTA', 'PSICOLOGO DE GUARDIA', 'OBSTETRICA DE GUARDIA',
    'PSICOPEDAGOGO DE PLANTA', 'ODONTOLOGO DE GUARDIA', 'OBSTETRICA DE PLANTA',
    'SUB-DIRECTOR (03)', 'LIC. EN TERAPIA OCUPACIONAL DE PLANTA'
  );
